include: package:flutter_lints/flutter.yaml

linter:

  rules:
    prefer_single_quotes: true

analyzer:
  strong-mode:

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    always_declare_return_types: error
    avoid_print: error
    missing_required_param: error
    missing_return: error
